apiVersion: v1
kind: Service
metadata:
  name: azdevopsapp
  namespace: namespace-workflow-1749189235030
  labels:
    app.kubernetes.io/name: azdevopsapp
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: azdevopsapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000