apiVersion: v1
kind: Service
metadata:
  name: aasa
  namespace: namespace-workflow-1749189577977
  labels:
    app.kubernetes.io/name: aasa
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: aasa
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000